# fly.toml app configuration file generated for ancient-star-1068 on 2023-11-15T13:01:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-star-1068"
primary_region = "lhr"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
